# 今日番剧插件配置
# 定时推送时间（Cron 表达式）
cronTime: '0 0 10 * * ?'
# 定时推送群号
groupList:

# 是否开启定时推送
isAutoPush: false
# 番剧表（key 为星期：0=周日 ... 6=周六）
schedule:
  0:
    - '亚托莉 -我挚爱的时光-（00:30）'
  1:
    - '今天没有番剧 喵'
  2:
    - '狼与香辛料（不定时）'
  3:
    - '这是妳与我的最后战场，或是开创世界的圣战（咕咕咕）'
    - '不时轻声地以俄语遮羞的邻座艾莉同学（22:30）'
  4:
    - '今天没有番剧 喵'
  5:
    - '神之塔（不定时）'
    - '关于我转生变成史莱姆这档事（22:30）'
  6:
    - '尼尔：自动人形（00:00）'
